keys:
  - &yubi 90F5B605DB46D2317AFDEEC4BDCD0C4E9F252898
  - &alpha age1skfvmh8ff3fghxucv5smeceavpsh354k0z3y42sau64v6h6x6d7sj8e3c9
  - &beta age18y20unz0zx00g6h2c64tt0l0a3h47ukaun4rn4ukggcretarppysprxuxv
  - &gamma age16wkq74zjg520vfp4rlq50yffp9p4tht6jtdyz5smzlkpdvg609pqnjshkg
  - &epsilon age1akax507dh5prm66uw3kufqxwxy5twuwqjv829jpy26aw2nt4g39s3g65fu
  - &delta age1p98um9682a6tppcxn602f0cfmgc4rkjclyuuqlu7gf578g9fz97suqp7wj
  - &gamma-new age17c3fvjye072zy06wy5azaqtupest47xu8gztdrvlg5erwwndp4ls4ss65v
  - &zetta age1dnzlu2savx6fyw48wte42l3ard3jf32whqd3q3reukwk66mcvvkqecnar6
creation_rules:
  - key_groups:
    - pgp:
      - *yubi
      age:
      - *alpha
      - *beta
      - *gamma
      - *epsilon
      - *delta
      - *gamma-new
      - *zetta
