keys:
  - &yubi 90F5B605DB46D2317AFDEEC4BDCD0C4E9F252898
  - &alpha age1skfvmh8ff3fghxucv5smeceavpsh354k0z3y42sau64v6h6x6d7sj8e3c9
  - &beta age18y20unz0zx00g6h2c64tt0l0a3h47ukaun4rn4ukggcretarppysprxuxv
  - &gamma age16wkq74zjg520vfp4rlq50yffp9p4tht6jtdyz5smzlkpdvg609pqnjshkg
  - &epsilon age1ewlzfu5f3vu393gqanhlquzdjszwpqwjej0pqh0vmqgrvggmc4pqydfhe6
  - &delta age1p98um9682a6tppcxn602f0cfmgc4rkjclyuuqlu7gf578g9fz97suqp7wj
  - &gamma-new age17c3fvjye072zy06wy5azaqtupest47xu8gztdrvlg5erwwndp4ls4ss65v
creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *yubi
      age:
      - *alpha
      - *beta
      - *gamma
      - *epsilon
      - *delta
      - *gamma-new
