keys:
  - &alpha age1skfvmh8ff3fghxucv5smeceavpsh354k0z3y42sau64v6h6x6d7sj8e3c9
  - &beta age18y20unz0zx00g6h2c64tt0l0a3h47ukaun4rn4ukggcretarppysprxuxv
  - &gamma age16wkq74zjg520vfp4rlq50yffp9p4tht6jtdyz5smzlkpdvg609pqnjshkg
  - &nixos-laptop age1kph642jksjds04ce5qtkqge5qqpdclz3k6elstgx0448vyh96s2q3hfd3s
  - &delta age1p98um9682a6tppcxn602f0cfmgc4rkjclyuuqlu7gf578g9fz97suqp7wj
creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *alpha
      - *beta
      - *gamma
      - *nixos-laptop
      - *delta
