keys:
  - &yubi 90F5B605DB46D2317AFDEEC4BDCD0C4E9F252898
  - &alpha age1skfvmh8ff3fghxucv5smeceavpsh354k0z3y42sau64v6h6x6d7sj8e3c9
  - &beta age1wselageuudgef2334l7tauyq06gyjpwlpge6ztmcxu6jcpkeu94sptum7g
  - &epsilon age1akax507dh5prm66uw3kufqxwxy5twuwqjv829jpy26aw2nt4g39s3g65fu
  - &delta age1p98um9682a6tppcxn602f0cfmgc4rkjclyuuqlu7gf578g9fz97suqp7wj
  - &gamma age1xw0t75c8yya0uk0j5klzgfssuvf5zjnh5jgw53l32fj2uv9z5p0s4gcmtd
  - &gammahost age1mnhkn6hgq2q5pkz93dy2kltz3cnfajeqsf35ew7p0n0ec5qnmqgqe0xfv2
  - &zetta age1dnzlu2savx6fyw48wte42l3ard3jf32whqd3q3reukwk66mcvvkqecnar6
  - &eta age1wsyazpnv8wj83qr5qpfq0hu62q2ljjdag4nzsekd43rremy0vdxsy326hh
creation_rules:
  - key_groups:
      - pgp:
          - *yubi
        age:
          - *alpha
          - *beta
          - *gamma
          - *epsilon
          - *delta
          - *zetta
          - *eta
          - *gammahost
