#!/usr/bin/env bash
# vi: ft=sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {
    [ $(cat "$bat/status") = Charging ] && echo "" && exit

    if [ "$per" -gt "90" ]; then
        icon=""
    elif [ "$per" -gt "70" ]; then
        icon=""
    elif [ "$per" -gt "50" ]; then
        icon=""
    elif [ "$per" -gt "30" ]; then
        icon=""
    elif [ "$per" -gt "10" ]; then
        icon=""
    else
        echo "" && exit
    fi
    if [ "$per" -le "10" ]; then
        notify-send -u critical "Battery Low" "Connect Charger"
    fi
    echo "$icon"
}

percent() {
    echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit

exit
