#!/usr/bin/env bash
# vi: ft=sh

dashboard() {
    LOCK_FILE="$HOME/.cache/eww-dashboard.lock"

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        eww open dashboard
    else
        eww close dashboard
        rm "$LOCK_FILE"
    fi
}

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        eww open calendar
    else
        eww close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "dashboard" ]; then
    dashboard &
elif [ "$1" = "audio" ]; then
    pavucontrol &
elif [ "$1" = "calendar" ]; then
    calendar &
fi
