#!/usr/bin/env sh
# vi: ft=sh

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    run() {
        eww open calendar
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        eww close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "launcher" ]; then
    @rofi@ -show run &
elif [ "$1" = "audio" ]; then
    @pavucontrol@ &
elif [ "$1" = "calendar" ]; then
    calendar &
fi
