#!/usr/bin/env sh
# vi: ft=sh

workspaces() {
    ws1=1
    ws2=2
    ws3=3
    ws4=4
    ws5=5
    ws6=6
    ws7=7
    ws8=8
    ws9=9
    ws0=0

    # Unoccupied
    un="0"

    occupied () {
        i3-msg -t get_workspaces | jq '[if .[].num == '$1' then 1 else 0 end] | add'
    }

    focused () {
        i3-msg -t get_workspaces | jq '[.[] | if .num == '$1' and .focused then 1 else 0 end] | add'
    }

    # check if Occupied
    o1=$(occupied "$ws1")
    o2=$(occupied "$ws2")
    o3=$(occupied "$ws3")
    o4=$(occupied "$ws4")
    o5=$(occupied "$ws5")
    o6=$(occupied "$ws6")
    o7=$(occupied "$ws7")
    o8=$(occupied "$ws8")
    o9=$(occupied "$ws9")
    o0=$(occupied "$ws0")

    # check if Focused
    f1=$(focused "$ws1")
    f2=$(focused "$ws2")
    f3=$(focused "$ws3")
    f4=$(focused "$ws4")
    f5=$(focused "$ws5")
    f6=$(focused "$ws6")
    f7=$(focused "$ws7")
    f8=$(focused "$ws8")
    f9=$(focused "$ws9")
    f0=$(focused "$ws0")

    # check if Urgent
    # u1=$(bspc query -D -d .urgent --names | grep 1)
    # u2=$(bspc query -D -d .urgent --names | grep 2)
    # u3=$(bspc query -D -d .urgent --names | grep 3)
    # u4=$(bspc query -D -d .urgent --names | grep 4)
    # u5=$(bspc query -D -d .urgent --names | grep 5)

    command="i3-msg workspace number"

    echo "\
        (box \
            :class \"workspaces\"\
            :space-evenly \"true\"\
            :orientation \"h\"\
            :halign \"start\"\
            :spacing \"10\"\
            (button :onclick \"$command $ws1 >/dev/null\" :class \"ws-$un$o1$f1\" \"\")\
            (button :onclick \"$command $ws2 >/dev/null\" :class \"ws-$un$o2$f2\" \"\")\
            (button :onclick \"$command $ws3 >/dev/null\" :class \"ws-$un$o3$f3\" \"\")\
            (button :onclick \"$command $ws4 >/dev/null\" :class \"ws-$un$o4$f4\" \"\")\
            (button :onclick \"$command $ws5 >/dev/null\" :class \"ws-$un$o5$f5\" \"\")\
            (button :onclick \"$command $ws6 >/dev/null\" :class \"ws-$un$o6$f6\" \"6\")\
            (button :onclick \"$command $ws7 >/dev/null\" :class \"ws-$un$o7$f7\" \"7\")\
            (button :onclick \"$command $ws8 >/dev/null\" :class \"ws-$un$o8$f8\" \"8\")\
            (button :onclick \"$command $ws9 >/dev/null\" :class \"ws-$un$o9$f9\" \"9\")\
            (button :onclick \"$command $ws0 >/dev/null\" :class \"ws-$un$o0$f0\" \"\"))"
}

workspaces
while true; do
    workspaces
    sleep 1
done
#bspc subscribe desktop node_transfer | while read -r _ ; do
    #workspaces
#done
