#!/usr/bin/env sh
# vi: ft=sh
#
# TODO: make more compositor-agnostic

workspaces() {
    active_workspace=${1:-$(hyrpctl activewindow -j | jq '.workspace.id')}
    command="@hyprctl@ dispatch workspace"

    focused () {
        if [[ "$1" == "$active_workspace" ]]; then
            echo 1
        else
            echo 0
        fi
    }

    raw_box="(box :class \"works\" :orientation \"v\" :halign \"center\" :valign \"start\" :space-evenly \"false\" :spacing \"10\""

    for wsid in $(@hyprctl@ workspaces -j | @jq@ '.[].id' | sort -h); do
        name=$(@hyprctl@ workspaces -j | @jq@ '[.[] | if .id == '$wsid' then .name else "" end] | join("")')
        foc=$(focused $wsid)

        raw_box="$raw_box (button :onclick \"$command $wsid\" :class \"ws-$foc\" $name)"
    done

    echo "$raw_box)"
}

function handle {
    if [[ ${1:0:9} == "workspace" ]]; then
        num=${1:11}
        workspaces $num
    elif [[ ${1:0:15} == "createworkspace" ]]; then
        workspaces
    elif [[ ${1:0:16} == "destroyworkspace" ]]; then
        workspaces
    elif [[ ${1:0:10} == "focusedmon" ]]; then
        mon=$(echo ${1:12} | cut -d ',' -f 1)
        num=$(echo ${1:12} | cut -d ',' -f 2)
        workspaces $num
    fi
}

workspaces
@socat@ -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
    handle "$event"
done
