{
 "title": "Sensors @ home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "sensor_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sensor_hum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sensor_gas{instance=\"10.200.0.5:9003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sensor_light", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 18 },
   "targets": [
    { "expr": "sensor_prs", "legendFormat": "__auto" }
   ]
  }
 ]
}