{
 "title": "Nginx analytics",
 "description": "Nginx access log analytics dashboard using Promtail and Loki v2+. Prometheus datasource is created from Loki service.\n\nhttps://grafana.com/grafana/dashboards/13865-fgc-nginx01-web-analytics/",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {}
   },
   {
    "name": "filename",
    "label": "filename",
    "query": {}
   },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [1h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [24h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [2d])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [7d])))"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  { "title": "Visitor Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Unique user visits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ `.*bot.*` | http_user_agent !~ `.*crawler.*` | http_user_agent != `worldping-api` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [1d])))",
     "legendFormat": "Unique user visit count"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [1d])))",
     "legendFormat": "Unique user visit count"
    }
   ]
  },
  { "title": "Sources & Behaviours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 27, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(5, sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers - Excluding bots",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_referer) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | http_referer != \"\" and http_referer !~ \".*?$host.*?\" | __error__=\"\" [$__interval]))) ",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages - Excluding '/'",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "topk(10,sum by (request_uri) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | request_uri != \"/\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 46 },
   "targets": [
    {
     "expr": "topk(5, sum by (http_referer) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | http_referer != \"\" and http_referer !~ \".*?$host.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 52 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  { "title": "Requests & HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"$filename\", host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=\"$filename\", host=\"$host\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate({filename=\"$filename\", host=\"$host\"} | json | status =~ `5\\d\\d` | __error__=`` [$__interval])) / 100) / sum(rate({filename=\"$filename\", host=\"$host\"} | json | __error__=`` [$__interval]))"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"$job\", host=\"$host\", filename=\"$filename\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"$job\", host=\"$host\", filename=\"$filename\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"$filename\", host=\"$host\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Recent requests (excluding 418)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{filename=\"$filename\", host=\"$host\"} | json | status != `418` | http_user_agent !~ `.*bot.*` | http_user_agent !~ `.*crawler.*` | request_uri != `/ts2021` | http_user_agent != `worldping-api` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | line_format `request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}} located {{.geoip_country_code}}`"
    }
   ]
  },
  { "title": "Request Statistics Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{filename=\"$filename\", host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({filename=\"$filename\", host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"$filename\", host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"$filename\", host=\"$host\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}