{
 "title": "Nginx",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests by Country Code",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(geoip_country_code) (rate({job=\"nginx_analytics\"} | json | __error__=`` | line_format `{{.geoip_country_code}}` | keep geoip_country_code [$__auto]))",
     "legendFormat": "{{.geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"nginx_analytics\"} | json | __error__=`` | keep status | line_format `{{.status}}` [$__auto])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by URI",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"nginx_analytics\"} | json | __error__=`` | keep request_uri | line_format `{{.request_uri}}` [$__auto])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap bytes(bytes_sent) | __error__=`` [1m]) by (host)",
     "legendFormat": "max ({{host}})"
    },
    {
     "expr": "avg_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap bytes(bytes_sent) | __error__=`` [1m]) by (host)",
     "legendFormat": "avg ({{host}})"
    },
    {
     "expr": "min_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap bytes(bytes_sent) | __error__=`` [1m]) by (host)",
     "legendFormat": "min ({{host}})"
    },
    {
     "expr": "quantile_over_time(0.99, {service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap bytes(bytes_sent) | __error__=`` [1m]) by (host)",
     "legendFormat": "99% quantile ({{host}})"
    }
   ]
  },
  {
   "title": "Request times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap request_time [1m]) by (host)",
     "legendFormat": "max ({{host}})"
    },
    {
     "expr": "avg_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap request_time [1m]) by (host)",
     "legendFormat": "avg ({{host}})"
    },
    {
     "expr": "min_over_time({service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap request_time [1m]) by (host)",
     "legendFormat": "min ({{host}})"
    },
    {
     "expr": "quantile_over_time(0.99, {service_name=\"nginx_analytics\"} | json | __error__=`` | unwrap request_time [1m]) by (host)",
     "legendFormat": "99% quantile ({{host}})"
    }
   ]
  }
 ]
}