{
 "title": "ZFS Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "zfs_pool_allocated_bytes", "legendFormat": "Allocated" },
    { "expr": "zfs_pool_free_bytes", "legendFormat": "Free" },
    { "expr": "zfs_pool_size_bytes", "legendFormat": "Size" }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zfs_pool_fragmentation_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deduplication",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zfs_pool_deduplication_ratio", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Leaked bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "zfs_pool_leaked_bytes", "legendFormat": "{{pool}}" }
   ]
  }
 ]
}