{
 "title": "System Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {}
   },
   {
    "name": "service",
    "label": "Systemd Unit(s)",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Share by host",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host) (rate({job=\"systemd-journal\", unit=~\"$service\", host=~\"$host\"} | logfmt [1m]))",
     "legendFormat": "{{.host}}"
    }
   ]
  },
  {
   "title": "Frequency per host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count by(host) (rate({job=\"systemd-journal\", unit=~\"$service\", host=~\"$host\"} | logfmt [1m]))",
     "legendFormat": "{{.host}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", host=~\"$host\", unit=~\"$service\"} | logfmt"
    }
   ]
  }
 ]
}