{
 "title": "Smart",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SMART General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SMART STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "smartctl_device_temperature", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_bytes{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power on Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Rotational Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_rotation_rate{job=\"delta\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}