# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];
  boot.binfmt.emulatedSystems = ["aarch64-linux"];

  # TODO move to disko
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/485e0a47-1e95-4d96-a732-2c65fcf7398a";
    fsType = "ext4";
  };
}
